### ISSUE TITLE
增加对gitlab的支持

### ISSUE THREAD

**Issue by lyj-cooyun** [lyj-cooyun/robot_pi#10]
支持对gitlab webhook的支持

直接在parsers文件夹里面增加一个gitlab.py就好了，照着github.py 写就好了

然后，在后台增加一个一个配置就可以了。

![image](https://user-images.githubusercontent.com/11983461/49196310-70b7ca00-f3c5-11e8-916d-d066e521784a.png)

**Comment by Wangzr** [comment]
我操，居然还能指派任务
